### ISSUE TITLE
LFS problems

### ISSUE THREAD

**Issue by andLaing** [next-exp/ANTEA#79]
I'm getting authentication errors when I try to push to my fork after resetting my local master to the current master. If I go back through the changes the error seems to start after PR #73 where there was a change to `localdb.PETALODB.sqlite3` .

Is anyone else getting a similar error? Any ideas how to solve it?

**Comment by paolafer** [comment]
I can push to my fork with no problem, and we have also approved and merged other PR after #73. Which error do you get?

**Comment by andLaing** [comment]
Yes, I noticed something was wrong when I tried to update to the current head. I reset to earlier merges to try and find where the problem started which seems to be the changes in PR #73.

I get this error:
`Pushing to https://github.com/andLaing/ANTEA.git
WARNING: Authentication error: Authentication required: Access forbidden. Check your access level.
batch response: Access forbidden. Check your access level.
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'https://github.com/andLaing/ANTEA.git'`

It's possible that there are some local problem that's causing it but I wasn't so far behind the head and only ~3 behind PR #73  so the change would have to be recent. I think all the commits since my last successful update are from your user, could someone else try to update (if they haven't already)? If successful, it would tell me that it's my local problem rather than some LFS change upstream.

**Comment by jmbenlloch** [comment]
It doesn't seem to be an LFS problem, the error is raised by `github.com` not by `next.ific.uv.es:8888` (our LFS server). I've checked your permissions on ANTEA. In principle all members of @next-exp should be able to push, in any case I've added you explicitly to the ANTEA developers list with write permissions. Maybe you can try again to see whether it works or not.

**Comment by andLaing** [comment]
Getting the same error still. Tried from neutrinos and same

**Comment by jmbenlloch** [comment]
Can you push to any other repository in github?

**Comment by andLaing** [comment]
Yes. I even just updated my year old IC so it's not specifically an LFS access thing.

I suppose it must be some odd local change, I'll maybe have to re-fork.

Has anyone else tried updating and pushing?

**Comment by carmenromo** [comment]
Yes, I just have done it and it works... Maybe you should explicitly download the new database?

**Comment by andLaing** [comment]
I tried that earlier when I first got the error, no help unfortunately.

I'll try redo-ing the fork.

**Comment by carmenromo** [comment]
How did you solve the problem?

**Comment by andLaing** [comment]
In the end I deleted my fork in github, re-forked and updated from the new origin/master. A bit brute force but it seems to have worked.
